### ISSUE TITLE
Analisis de app realidad aumentada (BilletesMx)

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-gregorio-8us#1]
[Reporte de app RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-equipo-gregorio-8us/files/14290710/Reporte.de.app.RA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
